#!/usr/bin/env python3
"""Build and verify the public OMAD V04 nutrition data artifact.

Branded labels override energy/macros/sodium where available. USDA SR28 foods
supply the wider micronutrient proxy. No cooking-retention correction is
applied. This is a planning model, not a medical assessment.
"""
from __future__ import annotations
import argparse
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "omad-fallback-meal" / "nutrition-data.json"
USDA_SR28 = {'11092': {'description': 'Broccoli, frozen, chopped, unprepared',
           'nutrients': {'calcium_mg': 56.0,
                         'carbs_g': 4.78,
                         'choline_mg': 14.9,
                         'copper_mg': 0.038,
                         'fat_g': 0.29,
                         'fiber_g': 3.0,
                         'folate_mcg': 67.0,
                         'iron_mg': 0.81,
                         'kcal': 26.0,
                         'magnesium_mg': 18.0,
                         'manganese_mg': 0.294,
                         'monounsaturated_fat_g': 0.02,
                         'niacin_mg': 0.47,
                         'omega3_ala_g': 0.105,
                         'omega3_dha_g': 0.0,
                         'omega3_epa_g': 0.0,
                         'pantothenic_mg': 0.279,
                         'phosphorus_mg': 50.0,
                         'polyunsaturated_fat_g': 0.136,
                         'potassium_mg': 212.0,
                         'protein_g': 2.81,
                         'riboflavin_mg': 0.096,
                         'saturated_fat_g': 0.044,
                         'selenium_mcg': 2.8,
                         'sodium_mg': 24.0,
                         'thiamin_mg': 0.053,
                         'vitamin_a_rae_mcg': 52.0,
                         'vitamin_b12_mcg': 0.0,
                         'vitamin_b6_mg': 0.13,
                         'vitamin_c_mg': 56.4,
                         'vitamin_d_mcg': 0.0,
                         'vitamin_e_mg': 1.22,
                         'vitamin_k_mcg': 81.1,
                         'zinc_mg': 0.48}},
 '11209': {'description': 'Eggplant, raw',
           'nutrients': {'calcium_mg': 9.0,
                         'carbs_g': 5.88,
                         'choline_mg': 6.9,
                         'copper_mg': 0.081,
                         'fat_g': 0.18,
                         'fiber_g': 3.0,
                         'folate_mcg': 22.0,
                         'iron_mg': 0.23,
                         'kcal': 25.0,
                         'magnesium_mg': 14.0,
                         'manganese_mg': 0.232,
                         'monounsaturated_fat_g': 0.016,
                         'niacin_mg': 0.649,
                         'omega3_ala_g': 0.013,
                         'omega3_dha_g': 0.0,
                         'omega3_epa_g': 0.0,
                         'pantothenic_mg': 0.281,
                         'phosphorus_mg': 24.0,
                         'polyunsaturated_fat_g': 0.076,
                         'potassium_mg': 229.0,
                         'protein_g': 0.98,
                         'riboflavin_mg': 0.037,
                         'saturated_fat_g': 0.034,
                         'selenium_mcg': 0.3,
                         'sodium_mg': 2.0,
                         'thiamin_mg': 0.039,
                         'vitamin_a_rae_mcg': 1.0,
                         'vitamin_b12_mcg': 0.0,
                         'vitamin_b6_mg': 0.084,
                         'vitamin_c_mg': 2.2,
                         'vitamin_d_mcg': 0.0,
                         'vitamin_e_mg': 0.3,
                         'vitamin_k_mcg': 3.5,
                         'zinc_mg': 0.16}},
 '11282': {'description': 'Onions, raw',
           'nutrients': {'calcium_mg': 23.0,
                         'carbs_g': 9.34,
                         'choline_mg': 6.1,
                         'copper_mg': 0.039,
                         'fat_g': 0.1,
                         'fiber_g': 1.7,
                         'folate_mcg': 19.0,
                         'iron_mg': 0.21,
                         'kcal': 40.0,
                         'magnesium_mg': 10.0,
                         'manganese_mg': 0.129,
                         'monounsaturated_fat_g': 0.013,
                         'niacin_mg': 0.116,
                         'omega3_ala_g': 0.004,
                         'omega3_dha_g': 0.0,
                         'omega3_epa_g': 0.0,
                         'pantothenic_mg': 0.123,
                         'phosphorus_mg': 29.0,
                         'polyunsaturated_fat_g': 0.017,
                         'potassium_mg': 146.0,
                         'protein_g': 1.1,
                         'riboflavin_mg': 0.027,
                         'saturated_fat_g': 0.042,
                         'selenium_mcg': 0.5,
                         'sodium_mg': 4.0,
                         'thiamin_mg': 0.046,
                         'vitamin_a_rae_mcg': 0.0,
                         'vitamin_b12_mcg': 0.0,
                         'vitamin_b6_mg': 0.12,
                         'vitamin_c_mg': 7.4,
                         'vitamin_d_mcg': 0.0,
                         'vitamin_e_mg': 0.02,
                         'vitamin_k_mcg': 0.4,
                         'zinc_mg': 0.17}},
 '11333': {'description': 'Peppers, sweet, green, raw',
           'nutrients': {'calcium_mg': 10.0,
                         'carbs_g': 4.64,
                         'choline_mg': 5.5,
                         'copper_mg': 0.066,
                         'fat_g': 0.17,
                         'fiber_g': 1.7,
                         'folate_mcg': 10.0,
                         'iron_mg': 0.34,
                         'kcal': 20.0,
                         'magnesium_mg': 10.0,
                         'manganese_mg': 0.122,
                         'monounsaturated_fat_g': 0.008,
                         'niacin_mg': 0.48,
                         'omega3_ala_g': 0.008,
                         'omega3_dha_g': 0.0,
                         'omega3_epa_g': 0.0,
                         'pantothenic_mg': 0.099,
                         'phosphorus_mg': 20.0,
                         'polyunsaturated_fat_g': 0.062,
                         'potassium_mg': 175.0,
                         'protein_g': 0.86,
                         'riboflavin_mg': 0.028,
                         'saturated_fat_g': 0.058,
                         'selenium_mcg': 0.0,
                         'sodium_mg': 3.0,
                         'thiamin_mg': 0.057,
                         'vitamin_a_rae_mcg': 18.0,
                         'vitamin_b12_mcg': 0.0,
                         'vitamin_b6_mg': 0.224,
                         'vitamin_c_mg': 80.4,
                         'vitamin_d_mcg': 0.0,
                         'vitamin_e_mg': 0.37,
                         'vitamin_k_mcg': 7.4,
                         'zinc_mg': 0.13}},
 '11477': {'description': 'Squash, summer, zucchini, includes skin, raw',
           'nutrients': {'calcium_mg': 16.0,
                         'carbs_g': 3.11,
                         'choline_mg': 9.5,
                         'copper_mg': 0.053,
                         'fat_g': 0.32,
                         'fiber_g': 1.0,
                         'folate_mcg': 24.0,
                         'iron_mg': 0.37,
                         'kcal': 17.0,
                         'magnesium_mg': 18.0,
                         'manganese_mg': 0.177,
                         'monounsaturated_fat_g': 0.011,
                         'niacin_mg': 0.451,
                         'omega3_ala_g': 0.061,
                         'omega3_dha_g': 0.0,
                         'omega3_epa_g': 0.0,
                         'pantothenic_mg': 0.204,
                         'phosphorus_mg': 38.0,
                         'polyunsaturated_fat_g': 0.091,
                         'potassium_mg': 261.0,
                         'protein_g': 1.21,
                         'riboflavin_mg': 0.094,
                         'saturated_fat_g': 0.084,
                         'selenium_mcg': 0.2,
                         'sodium_mg': 8.0,
                         'thiamin_mg': 0.045,
                         'vitamin_a_rae_mcg': 10.0,
                         'vitamin_b12_mcg': 0.0,
                         'vitamin_b6_mg': 0.163,
                         'vitamin_c_mg': 17.9,
                         'vitamin_d_mcg': 0.0,
                         'vitamin_e_mg': 0.12,
                         'vitamin_k_mcg': 4.3,
                         'zinc_mg': 0.32}},
 '11821': {'description': 'Peppers, sweet, red, raw',
           'nutrients': {'calcium_mg': 7.0,
                         'carbs_g': 6.03,
                         'choline_mg': 5.6,
                         'copper_mg': 0.017,
                         'fat_g': 0.3,
                         'fiber_g': 2.1,
                         'folate_mcg': 46.0,
                         'iron_mg': 0.43,
                         'kcal': 31.0,
                         'magnesium_mg': 12.0,
                         'manganese_mg': 0.112,
                         'monounsaturated_fat_g': 0.003,
                         'niacin_mg': 0.979,
                         'omega3_ala_g': 0.025,
                         'omega3_dha_g': 0.0,
                         'omega3_epa_g': 0.0,
                         'pantothenic_mg': 0.317,
                         'phosphorus_mg': 26.0,
                         'polyunsaturated_fat_g': 0.07,
                         'potassium_mg': 211.0,
                         'protein_g': 0.99,
                         'riboflavin_mg': 0.085,
                         'saturated_fat_g': 0.027,
                         'selenium_mcg': 0.1,
                         'sodium_mg': 4.0,
                         'thiamin_mg': 0.054,
                         'vitamin_a_rae_mcg': 157.0,
                         'vitamin_b12_mcg': 0.0,
                         'vitamin_b6_mg': 0.291,
                         'vitamin_c_mg': 127.7,
                         'vitamin_d_mcg': 0.0,
                         'vitamin_e_mg': 1.58,
                         'vitamin_k_mcg': 4.9,
                         'zinc_mg': 0.25}},
 '11951': {'description': 'Peppers, sweet, yellow, raw',
           'nutrients': {'calcium_mg': 11.0,
                         'carbs_g': 6.32,
                         'copper_mg': 0.107,
                         'fat_g': 0.21,
                         'fiber_g': 0.9,
                         'folate_mcg': 26.0,
                         'iron_mg': 0.46,
                         'kcal': 27.0,
                         'magnesium_mg': 12.0,
                         'manganese_mg': 0.117,
                         'niacin_mg': 0.89,
                         'pantothenic_mg': 0.168,
                         'phosphorus_mg': 24.0,
                         'potassium_mg': 212.0,
                         'protein_g': 1.0,
                         'riboflavin_mg': 0.025,
                         'saturated_fat_g': 0.031,
                         'selenium_mcg': 0.3,
                         'sodium_mg': 2.0,
                         'thiamin_mg': 0.028,
                         'vitamin_a_rae_mcg': 10.0,
                         'vitamin_b12_mcg': 0.0,
                         'vitamin_b6_mg': 0.168,
                         'vitamin_c_mg': 183.5,
                         'vitamin_d_mcg': 0.0,
                         'zinc_mg': 0.17}},
 '1256': {'description': 'Yogurt, Greek, plain, nonfat',
          'nutrients': {'calcium_mg': 110.0,
                        'carbs_g': 3.6,
                        'choline_mg': 15.1,
                        'copper_mg': 0.017,
                        'fat_g': 0.39,
                        'fiber_g': 0.0,
                        'folate_mcg': 7.0,
                        'iron_mg': 0.07,
                        'kcal': 59.0,
                        'magnesium_mg': 11.0,
                        'manganese_mg': 0.009,
                        'monounsaturated_fat_g': 0.053,
                        'niacin_mg': 0.208,
                        'omega3_ala_g': 0.001,
                        'omega3_dha_g': 0.0,
                        'omega3_epa_g': 0.0,
                        'pantothenic_mg': 0.331,
                        'phosphorus_mg': 135.0,
                        'polyunsaturated_fat_g': 0.012,
                        'potassium_mg': 141.0,
                        'protein_g': 10.19,
                        'riboflavin_mg': 0.278,
                        'saturated_fat_g': 0.117,
                        'selenium_mcg': 9.7,
                        'sodium_mg': 36.0,
                        'thiamin_mg': 0.023,
                        'vitamin_a_rae_mcg': 1.0,
                        'vitamin_b12_mcg': 0.75,
                        'vitamin_b6_mg': 0.063,
                        'vitamin_c_mg': 0.0,
                        'vitamin_d_mcg': 0.0,
                        'vitamin_e_mg': 0.01,
                        'vitamin_k_mcg': 0.0,
                        'zinc_mg': 0.52}},
 '15236': {'description': 'Fish, salmon, Atlantic, farmed, raw',
           'nutrients': {'calcium_mg': 9.0,
                         'carbs_g': 0.0,
                         'choline_mg': 78.5,
                         'copper_mg': 0.045,
                         'fat_g': 13.42,
                         'fiber_g': 0.0,
                         'folate_mcg': 26.0,
                         'iron_mg': 0.34,
                         'kcal': 208.0,
                         'magnesium_mg': 27.0,
                         'manganese_mg': 0.011,
                         'monounsaturated_fat_g': 3.77,
                         'niacin_mg': 8.672,
                         'omega3_ala_g': 0.148,
                         'omega3_dha_g': 1.104,
                         'omega3_epa_g': 0.862,
                         'pantothenic_mg': 1.547,
                         'phosphorus_mg': 240.0,
                         'polyunsaturated_fat_g': 3.886,
                         'potassium_mg': 363.0,
                         'protein_g': 20.42,
                         'riboflavin_mg': 0.155,
                         'saturated_fat_g': 3.05,
                         'selenium_mcg': 24.0,
                         'sodium_mg': 59.0,
                         'thiamin_mg': 0.207,
                         'vitamin_a_rae_mcg': 58.0,
                         'vitamin_b12_mcg': 3.23,
                         'vitamin_b6_mg': 0.636,
                         'vitamin_c_mg': 3.9,
                         'vitamin_d_mcg': 11.0,
                         'vitamin_e_mg': 3.55,
                         'vitamin_k_mcg': 0.5,
                         'zinc_mg': 0.36}},
 '16359': {'description': 'Chickpeas (garbanzo beans, bengal gram), mature seeds, canned, drained, rinsed in tap water',
           'nutrients': {'calcium_mg': 43.0,
                         'carbs_g': 22.87,
                         'copper_mg': 0.25,
                         'fat_g': 2.47,
                         'fiber_g': 6.3,
                         'folate_mcg': 41.0,
                         'iron_mg': 0.98,
                         'kcal': 138.0,
                         'magnesium_mg': 24.0,
                         'manganese_mg': 0.8,
                         'monounsaturated_fat_g': 0.485,
                         'niacin_mg': 0.125,
                         'omega3_ala_g': 0.036,
                         'omega3_dha_g': 0.0,
                         'omega3_epa_g': 0.0,
                         'phosphorus_mg': 80.0,
                         'polyunsaturated_fat_g': 0.962,
                         'potassium_mg': 109.0,
                         'protein_g': 7.04,
                         'riboflavin_mg': 0.015,
                         'saturated_fat_g': 0.213,
                         'selenium_mcg': 3.1,
                         'sodium_mg': 212.0,
                         'thiamin_mg': 0.025,
                         'vitamin_a_rae_mcg': 1.0,
                         'vitamin_b12_mcg': 0.0,
                         'vitamin_b6_mg': 0.116,
                         'vitamin_c_mg': 0.1,
                         'vitamin_d_mcg': 0.0,
                         'vitamin_e_mg': 0.29,
                         'vitamin_k_mcg': 3.4,
                         'zinc_mg': 0.59}},
 '4053': {'description': 'Oil, olive, salad or cooking',
          'nutrients': {'calcium_mg': 1.0,
                        'carbs_g': 0.0,
                        'choline_mg': 0.3,
                        'copper_mg': 0.0,
                        'fat_g': 100.0,
                        'fiber_g': 0.0,
                        'folate_mcg': 0.0,
                        'iron_mg': 0.56,
                        'kcal': 884.0,
                        'magnesium_mg': 0.0,
                        'manganese_mg': 0.0,
                        'monounsaturated_fat_g': 72.961,
                        'niacin_mg': 0.0,
                        'omega3_ala_g': 0.761,
                        'omega3_dha_g': 0.0,
                        'omega3_epa_g': 0.0,
                        'pantothenic_mg': 0.0,
                        'phosphorus_mg': 0.0,
                        'polyunsaturated_fat_g': 10.523,
                        'potassium_mg': 1.0,
                        'protein_g': 0.0,
                        'riboflavin_mg': 0.0,
                        'saturated_fat_g': 13.808,
                        'selenium_mcg': 0.0,
                        'sodium_mg': 2.0,
                        'thiamin_mg': 0.0,
                        'vitamin_a_rae_mcg': 0.0,
                        'vitamin_b12_mcg': 0.0,
                        'vitamin_b6_mg': 0.0,
                        'vitamin_c_mg': 0.0,
                        'vitamin_d_mcg': 0.0,
                        'vitamin_e_mg': 14.35,
                        'vitamin_k_mcg': 60.2,
                        'zinc_mg': 0.0}},
 '4060': {'description': 'Oil, sunflower, linoleic (less than 60%)',
          'nutrients': {'calcium_mg': 0.0,
                        'carbs_g': 0.0,
                        'fat_g': 100.0,
                        'fiber_g': 0.0,
                        'folate_mcg': 0.0,
                        'iron_mg': 0.03,
                        'kcal': 884.0,
                        'magnesium_mg': 0.0,
                        'monounsaturated_fat_g': 45.4,
                        'niacin_mg': 0.0,
                        'omega3_ala_g': 0.2,
                        'omega3_dha_g': 0.0,
                        'omega3_epa_g': 0.0,
                        'pantothenic_mg': 0.0,
                        'phosphorus_mg': 0.0,
                        'polyunsaturated_fat_g': 40.1,
                        'potassium_mg': 0.0,
                        'protein_g': 0.0,
                        'riboflavin_mg': 0.0,
                        'saturated_fat_g': 10.1,
                        'selenium_mcg': 0.0,
                        'sodium_mg': 0.0,
                        'thiamin_mg': 0.0,
                        'vitamin_a_rae_mcg': 0.0,
                        'vitamin_b12_mcg': 0.0,
                        'vitamin_b6_mg': 0.0,
                        'vitamin_c_mg': 0.0,
                        'vitamin_e_mg': 41.08,
                        'vitamin_k_mcg': 5.4,
                        'zinc_mg': 0.0}},
 '5064': {'description': 'Chicken, broilers or fryers, breast, meat only, cooked, roasted',
          'nutrients': {'calcium_mg': 15.0,
                        'carbs_g': 0.0,
                        'choline_mg': 85.3,
                        'copper_mg': 0.049,
                        'fat_g': 3.57,
                        'fiber_g': 0.0,
                        'folate_mcg': 4.0,
                        'iron_mg': 1.04,
                        'kcal': 165.0,
                        'magnesium_mg': 29.0,
                        'manganese_mg': 0.017,
                        'monounsaturated_fat_g': 1.24,
                        'niacin_mg': 13.712,
                        'omega3_ala_g': 0.03,
                        'omega3_dha_g': 0.02,
                        'omega3_epa_g': 0.01,
                        'pantothenic_mg': 0.965,
                        'phosphorus_mg': 228.0,
                        'polyunsaturated_fat_g': 0.77,
                        'potassium_mg': 256.0,
                        'protein_g': 31.02,
                        'riboflavin_mg': 0.114,
                        'saturated_fat_g': 1.01,
                        'selenium_mcg': 27.6,
                        'sodium_mg': 74.0,
                        'thiamin_mg': 0.07,
                        'vitamin_a_rae_mcg': 6.0,
                        'vitamin_b12_mcg': 0.34,
                        'vitamin_b6_mg': 0.6,
                        'vitamin_c_mg': 0.0,
                        'vitamin_d_mcg': 0.1,
                        'vitamin_e_mg': 0.27,
                        'vitamin_k_mcg': 0.3,
                        'zinc_mg': 1.0}},
 '9037': {'description': 'Avocados, raw, all commercial varieties',
          'nutrients': {'calcium_mg': 12.0,
                        'carbs_g': 8.53,
                        'choline_mg': 14.2,
                        'copper_mg': 0.19,
                        'fat_g': 14.66,
                        'fiber_g': 6.7,
                        'folate_mcg': 81.0,
                        'iron_mg': 0.55,
                        'kcal': 160.0,
                        'magnesium_mg': 29.0,
                        'manganese_mg': 0.142,
                        'monounsaturated_fat_g': 9.799,
                        'niacin_mg': 1.738,
                        'omega3_ala_g': 0.111,
                        'omega3_dha_g': 0.0,
                        'omega3_epa_g': 0.0,
                        'pantothenic_mg': 1.389,
                        'phosphorus_mg': 52.0,
                        'polyunsaturated_fat_g': 1.816,
                        'potassium_mg': 485.0,
                        'protein_g': 2.0,
                        'riboflavin_mg': 0.13,
                        'saturated_fat_g': 2.126,
                        'selenium_mcg': 0.4,
                        'sodium_mg': 7.0,
                        'thiamin_mg': 0.067,
                        'vitamin_a_rae_mcg': 7.0,
                        'vitamin_b12_mcg': 0.0,
                        'vitamin_b6_mg': 0.257,
                        'vitamin_c_mg': 10.0,
                        'vitamin_d_mcg': 0.0,
                        'vitamin_e_mg': 2.07,
                        'vitamin_k_mcg': 21.0,
                        'zinc_mg': 0.64}},
 '9048': {'description': 'Blackberries, frozen, unsweetened',
          'nutrients': {'calcium_mg': 29.0,
                        'carbs_g': 15.67,
                        'choline_mg': 8.5,
                        'copper_mg': 0.12,
                        'fat_g': 0.43,
                        'fiber_g': 5.0,
                        'folate_mcg': 34.0,
                        'iron_mg': 0.8,
                        'kcal': 64.0,
                        'magnesium_mg': 22.0,
                        'manganese_mg': 1.223,
                        'monounsaturated_fat_g': 0.041,
                        'niacin_mg': 1.207,
                        'omega3_ala_g': 0.082,
                        'omega3_dha_g': 0.0,
                        'omega3_epa_g': 0.0,
                        'pantothenic_mg': 0.151,
                        'phosphorus_mg': 30.0,
                        'polyunsaturated_fat_g': 0.245,
                        'potassium_mg': 140.0,
                        'protein_g': 1.18,
                        'riboflavin_mg': 0.046,
                        'saturated_fat_g': 0.015,
                        'selenium_mcg': 0.4,
                        'sodium_mg': 1.0,
                        'thiamin_mg': 0.029,
                        'vitamin_a_rae_mcg': 6.0,
                        'vitamin_b12_mcg': 0.0,
                        'vitamin_b6_mg': 0.061,
                        'vitamin_c_mg': 3.1,
                        'vitamin_d_mcg': 0.0,
                        'vitamin_e_mg': 1.17,
                        'vitamin_k_mcg': 19.8,
                        'zinc_mg': 0.25}},
 '9054': {'description': 'Blueberries, frozen, unsweetened',
          'nutrients': {'calcium_mg': 8.0,
                        'carbs_g': 12.17,
                        'choline_mg': 5.1,
                        'copper_mg': 0.033,
                        'fat_g': 0.64,
                        'fiber_g': 2.7,
                        'folate_mcg': 7.0,
                        'iron_mg': 0.18,
                        'kcal': 51.0,
                        'magnesium_mg': 5.0,
                        'manganese_mg': 0.147,
                        'monounsaturated_fat_g': 0.091,
                        'niacin_mg': 0.52,
                        'omega3_ala_g': 0.112,
                        'omega3_dha_g': 0.0,
                        'omega3_epa_g': 0.0,
                        'pantothenic_mg': 0.125,
                        'phosphorus_mg': 11.0,
                        'polyunsaturated_fat_g': 0.279,
                        'potassium_mg': 54.0,
                        'protein_g': 0.42,
                        'riboflavin_mg': 0.037,
                        'saturated_fat_g': 0.053,
                        'selenium_mcg': 0.1,
                        'sodium_mg': 1.0,
                        'thiamin_mg': 0.032,
                        'vitamin_a_rae_mcg': 2.0,
                        'vitamin_b12_mcg': 0.0,
                        'vitamin_b6_mg': 0.059,
                        'vitamin_c_mg': 2.5,
                        'vitamin_d_mcg': 0.0,
                        'vitamin_e_mg': 0.48,
                        'vitamin_k_mcg': 16.4,
                        'zinc_mg': 0.07}},
 '9083': {'description': 'Currants, european black, raw',
          'nutrients': {'calcium_mg': 55.0,
                        'carbs_g': 15.38,
                        'copper_mg': 0.086,
                        'fat_g': 0.41,
                        'iron_mg': 1.54,
                        'kcal': 63.0,
                        'magnesium_mg': 24.0,
                        'manganese_mg': 0.256,
                        'monounsaturated_fat_g': 0.058,
                        'niacin_mg': 0.3,
                        'omega3_ala_g': 0.072,
                        'pantothenic_mg': 0.398,
                        'phosphorus_mg': 59.0,
                        'polyunsaturated_fat_g': 0.179,
                        'potassium_mg': 322.0,
                        'protein_g': 1.4,
                        'riboflavin_mg': 0.05,
                        'saturated_fat_g': 0.034,
                        'sodium_mg': 2.0,
                        'thiamin_mg': 0.05,
                        'vitamin_a_rae_mcg': 12.0,
                        'vitamin_b12_mcg': 0.0,
                        'vitamin_b6_mg': 0.066,
                        'vitamin_c_mg': 181.0,
                        'vitamin_e_mg': 1.0,
                        'zinc_mg': 0.27}},
 '9084': {'description': 'Currants, red and white, raw',
          'nutrients': {'calcium_mg': 33.0,
                        'carbs_g': 13.8,
                        'choline_mg': 7.6,
                        'copper_mg': 0.107,
                        'fat_g': 0.2,
                        'fiber_g': 4.3,
                        'folate_mcg': 8.0,
                        'iron_mg': 1.0,
                        'kcal': 56.0,
                        'magnesium_mg': 13.0,
                        'manganese_mg': 0.186,
                        'monounsaturated_fat_g': 0.028,
                        'niacin_mg': 0.1,
                        'omega3_ala_g': 0.035,
                        'omega3_dha_g': 0.0,
                        'omega3_epa_g': 0.0,
                        'pantothenic_mg': 0.064,
                        'phosphorus_mg': 44.0,
                        'polyunsaturated_fat_g': 0.088,
                        'potassium_mg': 275.0,
                        'protein_g': 1.4,
                        'riboflavin_mg': 0.05,
                        'saturated_fat_g': 0.017,
                        'selenium_mcg': 0.6,
                        'sodium_mg': 1.0,
                        'thiamin_mg': 0.04,
                        'vitamin_a_rae_mcg': 2.0,
                        'vitamin_b12_mcg': 0.0,
                        'vitamin_b6_mg': 0.07,
                        'vitamin_c_mg': 41.0,
                        'vitamin_d_mcg': 0.0,
                        'vitamin_e_mg': 0.1,
                        'vitamin_k_mcg': 11.0,
                        'zinc_mg': 0.23}},
 '9318': {'description': 'Strawberries, frozen, unsweetened',
          'nutrients': {'calcium_mg': 16.0,
                        'carbs_g': 9.13,
                        'choline_mg': 5.7,
                        'copper_mg': 0.049,
                        'fat_g': 0.11,
                        'fiber_g': 2.1,
                        'folate_mcg': 17.0,
                        'iron_mg': 0.75,
                        'kcal': 35.0,
                        'magnesium_mg': 11.0,
                        'manganese_mg': 0.29,
                        'monounsaturated_fat_g': 0.015,
                        'niacin_mg': 0.462,
                        'omega3_ala_g': 0.023,
                        'omega3_dha_g': 0.0,
                        'omega3_epa_g': 0.0,
                        'pantothenic_mg': 0.108,
                        'phosphorus_mg': 13.0,
                        'polyunsaturated_fat_g': 0.054,
                        'potassium_mg': 148.0,
                        'protein_g': 0.43,
                        'riboflavin_mg': 0.037,
                        'saturated_fat_g': 0.006,
                        'selenium_mcg': 0.7,
                        'sodium_mg': 2.0,
                        'thiamin_mg': 0.022,
                        'vitamin_a_rae_mcg': 2.0,
                        'vitamin_b12_mcg': 0.0,
                        'vitamin_b6_mg': 0.028,
                        'vitamin_c_mg': 41.2,
                        'vitamin_d_mcg': 0.0,
                        'vitamin_e_mg': 0.29,
                        'vitamin_k_mcg': 2.2,
                        'zinc_mg': 0.13}},
 '9518': {'description': 'Raspberries, frozen, unsweetened',
          'nutrients': {'calcium_mg': 25.0,
                        'carbs_g': 11.94,
                        'choline_mg': 12.3,
                        'copper_mg': 0.09,
                        'fat_g': 0.65,
                        'fiber_g': 6.5,
                        'folate_mcg': 21.0,
                        'iron_mg': 0.69,
                        'kcal': 52.0,
                        'magnesium_mg': 22.0,
                        'manganese_mg': 0.67,
                        'niacin_mg': 0.598,
                        'omega3_ala_g': 0.126,
                        'omega3_dha_g': 0.0,
                        'omega3_epa_g': 0.0,
                        'pantothenic_mg': 0.329,
                        'phosphorus_mg': 29.0,
                        'potassium_mg': 151.0,
                        'protein_g': 1.2,
                        'riboflavin_mg': 0.038,
                        'selenium_mcg': 0.2,
                        'sodium_mg': 1.0,
                        'thiamin_mg': 0.032,
                        'vitamin_a_rae_mcg': 2.0,
                        'vitamin_b12_mcg': 0.0,
                        'vitamin_b6_mg': 0.055,
                        'vitamin_c_mg': 26.2,
                        'vitamin_d_mcg': 0.0,
                        'vitamin_e_mg': 0.87,
                        'vitamin_k_mcg': 7.8,
                        'zinc_mg': 0.42}}}

# Additional SR28 records required by the verified AH Italian vegetable mix.
USDA_SR28.update({
  '11124': {'description': 'Carrots, raw', 'nutrients': {'protein_g': 0.93, 'fat_g': 0.24, 'carbs_g': 9.58, 'kcal': 41.0, 'fiber_g': 2.8, 'calcium_mg': 33.0, 'iron_mg': 0.3, 'magnesium_mg': 12.0, 'phosphorus_mg': 35.0, 'potassium_mg': 320.0, 'sodium_mg': 69.0, 'zinc_mg': 0.24, 'copper_mg': 0.045, 'manganese_mg': 0.143, 'selenium_mcg': 0.1, 'vitamin_a_rae_mcg': 835.0, 'vitamin_e_mg': 0.66, 'vitamin_d_mcg': 0.0, 'vitamin_c_mg': 5.9, 'thiamin_mg': 0.066, 'riboflavin_mg': 0.058, 'niacin_mg': 0.983, 'pantothenic_mg': 0.273, 'vitamin_b6_mg': 0.138, 'vitamin_b12_mcg': 0.0, 'choline_mg': 8.8, 'vitamin_k_mcg': 13.2, 'folate_mcg': 19.0, 'saturated_fat_g': 0.037}},
  '11246': {'description': 'Leeks, (bulb and lower leaf-portion), raw', 'nutrients': {'protein_g': 1.5, 'fat_g': 0.3, 'carbs_g': 14.15, 'kcal': 61.0, 'fiber_g': 1.8, 'calcium_mg': 59.0, 'iron_mg': 2.1, 'magnesium_mg': 28.0, 'phosphorus_mg': 35.0, 'potassium_mg': 180.0, 'sodium_mg': 20.0, 'zinc_mg': 0.12, 'copper_mg': 0.12, 'manganese_mg': 0.481, 'selenium_mcg': 1.0, 'vitamin_a_rae_mcg': 83.0, 'vitamin_e_mg': 0.92, 'vitamin_d_mcg': 0.0, 'vitamin_c_mg': 12.0, 'thiamin_mg': 0.06, 'riboflavin_mg': 0.03, 'niacin_mg': 0.4, 'pantothenic_mg': 0.14, 'vitamin_b6_mg': 0.233, 'vitamin_b12_mcg': 0.0, 'choline_mg': 9.5, 'vitamin_k_mcg': 47.0, 'folate_mcg': 64.0, 'saturated_fat_g': 0.04}},
})

# Cooked asparagus proxy for Muscle Meat's blanched, IQF green asparagus.
USDA_SR28['11012'] = {'description': 'Asparagus, cooked, boiled, drained', 'nutrients': {'protein_g': 2.4, 'fat_g': 0.22, 'carbs_g': 4.11, 'kcal': 22.0, 'fiber_g': 2.0, 'calcium_mg': 23.0, 'iron_mg': 0.91, 'magnesium_mg': 14.0, 'phosphorus_mg': 54.0, 'potassium_mg': 224.0, 'sodium_mg': 14.0, 'zinc_mg': 0.6, 'copper_mg': 0.165, 'manganese_mg': 0.154, 'selenium_mcg': 6.1, 'vitamin_a_rae_mcg': 50.0, 'vitamin_e_mg': 1.5, 'vitamin_d_mcg': 0.0, 'vitamin_c_mg': 7.7, 'thiamin_mg': 0.162, 'riboflavin_mg': 0.139, 'niacin_mg': 1.084, 'pantothenic_mg': 0.225, 'vitamin_b6_mg': 0.079, 'vitamin_b12_mcg': 0.0, 'choline_mg': 26.1, 'vitamin_k_mcg': 50.6, 'folate_mcg': 149.0, 'saturated_fat_g': 0.048}}

TARGETS = {
    "kcal": (2000, "kcal", "Reference energy"),
    "protein_g": (56, "g", "Protein RDA"),
    "carbs_g": (130, "g", "Carbohydrate RDA"),
    "fiber_g": (38, "g", "Fibre AI"),
    "fat_g": (78, "g", "Display reference"),
    "saturated_fat_g": (20, "g", "Upper display limit"),
    "vitamin_a_rae_mcg": (900, "µg RAE", "Vitamin A RDA"),
    "vitamin_c_mg": (90, "mg", "Vitamin C RDA"),
    "vitamin_d_mcg": (15, "µg", "Vitamin D RDA"),
    "vitamin_e_mg": (15, "mg", "Vitamin E RDA"),
    "vitamin_k_mcg": (120, "µg", "Vitamin K AI"),
    "thiamin_mg": (1.2, "mg", "Thiamin RDA"),
    "riboflavin_mg": (1.3, "mg", "Riboflavin RDA"),
    "niacin_mg": (16, "mg", "Niacin RDA"),
    "pantothenic_mg": (5, "mg", "Pantothenic acid AI"),
    "vitamin_b6_mg": (1.3, "mg", "Vitamin B6 RDA"),
    "folate_mcg": (400, "µg", "Folate RDA"),
    "vitamin_b12_mcg": (2.4, "µg", "Vitamin B12 RDA"),
    "calcium_mg": (1000, "mg", "Calcium RDA"),
    "iron_mg": (8, "mg", "Iron RDA"),
    "magnesium_mg": (420, "mg", "Magnesium RDA"),
    "phosphorus_mg": (700, "mg", "Phosphorus RDA"),
    "potassium_mg": (3400, "mg", "Potassium AI"),
    "zinc_mg": (11, "mg", "Zinc RDA"),
    "copper_mg": (0.9, "mg", "Copper RDA"),
    "manganese_mg": (2.3, "mg", "Manganese AI"),
    "selenium_mcg": (55, "µg", "Selenium RDA"),
    "sodium_mg": (2300, "mg", "Sodium upper limit"),
    "choline_mg": (550, "mg", "Choline AI"),
    "omega3_ala_g": (1.6, "g", "ALA AI"),
    "omega3_epa_dha_mg": (250, "mg", "EPA+DHA display reference"),
}

LABELS = {
    "kcal":"Energy", "protein_g":"Protein", "carbs_g":"Carbohydrate", "fiber_g":"Fibre", "fat_g":"Fat",
    "saturated_fat_g":"Saturated fat", "vitamin_a_rae_mcg":"Vitamin A", "vitamin_c_mg":"Vitamin C",
    "vitamin_d_mcg":"Vitamin D", "vitamin_e_mg":"Vitamin E", "vitamin_k_mcg":"Vitamin K", "thiamin_mg":"Thiamin (B1)",
    "riboflavin_mg":"Riboflavin (B2)", "niacin_mg":"Niacin (B3)", "pantothenic_mg":"Pantothenic acid (B5)",
    "vitamin_b6_mg":"Vitamin B6", "folate_mcg":"Folate (B9)", "vitamin_b12_mcg":"Vitamin B12", "calcium_mg":"Calcium",
    "iron_mg":"Iron", "magnesium_mg":"Magnesium", "phosphorus_mg":"Phosphorus", "potassium_mg":"Potassium",
    "zinc_mg":"Zinc", "copper_mg":"Copper", "manganese_mg":"Manganese", "selenium_mcg":"Selenium",
    "sodium_mg":"Sodium", "choline_mg":"Choline", "omega3_ala_g":"Omega-3 ALA", "omega3_epa_dha_mg":"Omega-3 EPA + DHA",
}

PRODUCTS = {
  "chicken": {
    "name":"Muscle Meat roasted chicken breast strips, natural", "grams":250,
    "package":"2.5 kg IQF bag", "package_price":29.95, "cost":29.95/2500*250,
    "url":"https://musclemeat.nl/product/kant-en-klare-roasted-kipfiletreepjes-naturel/",
    "components":[(5064,250)],
    "overrides":{"kcal":115*2.5,"protein_g":23.4*2.5,"carbs_g":1.2*2.5,"fat_g":1.8*2.5,"saturated_fat_g":0.7*2.5,"sodium_mg":0.8*2.5*1000/2.54},
    "evidence":"Muscle Meat product label; USDA cooked chicken breast proxy for micros"
  },
  "salmon": {
    "name":"AH frozen Atlantic salmon fillets", "grams":250,
    "package":"250 g / 2 × 125 g", "package_price":4.95, "cost":4.95,
    "url":"https://www.ah.nl/producten/product/wi135757/ah-zalmfilet",
    "components":[(15236,250)],
    "overrides":{"kcal":179*2.5,"protein_g":20*2.5,"carbs_g":0,"fat_g":11*2.5,"saturated_fat_g":2*2.5,"sodium_mg":0.1*2.5*1000/2.54,"omega3_epa_g":1.85795,"omega3_dha_g":2.37955},
    "evidence":"Primary AH API label; USDA Atlantic farmed salmon proxy for wider micros, with EPA/DHA ratio scaled to the label's total omega-3 ceiling"
  },
  "chickpeas": {
    "name":"AH Terra chickpeas, one drained can", "grams":265,
    "package":"400 g can / 265 g drained", "package_price":0.99, "cost":0.99,
    "url":"https://www.ah.nl/producten/product/wi167873/ah-terra-kikkererwten",
    "components":[(16359,265)],
    "overrides":{"kcal":115*2.65,"protein_g":6.9*2.65,"carbs_g":14*2.65,"fat_g":2.5*2.65,"saturated_fat_g":0.8*2.65,"fiber_g":4.6*2.65,"sodium_mg":0},
    "evidence":"Primary AH API label for drained amount/macros; USDA canned drained/rinsed chickpeas proxy for wider micros"
  },
  "broccoli": {
    "name":"Muscle Meat precooked broccoli florets", "grams":250,
    "package":"2.5 kg IQF bag / 10 meals", "package_price":7.95, "cost":7.95/10,
    "url":"https://musclemeat.nl/product/broccoliroosjes/",
    "components":[(11092,250)],
    "overrides":{"kcal":38*2.5,"protein_g":3.3*2.5,"carbs_g":2.3*2.5,"fat_g":0.9*2.5,"saturated_fat_g":0.1*2.5,"fiber_g":3.6*2.5,"sodium_mg":0.013*2.5*1000},
    "evidence":"Muscle Meat product label; USDA frozen broccoli proxy for wider micros"
  },
  "asparagus": {
    "name":"Muscle Meat precooked green asparagus", "grams":100,
    "package":"1 kg IQF bag / 10 meals", "package_price":12.45, "cost":12.45/10,
    "url":"https://musclemeat.nl/product/groene-asperges/",
    "components":[(11012,100)],
    "overrides":{"kcal":28,"protein_g":2.9,"carbs_g":2,"fat_g":0.6,"saturated_fat_g":0.1,"fiber_g":1.7,"sodium_mg":0.003*1000/2.54},
    "evidence":"Muscle Meat product label; USDA cooked drained asparagus proxy for wider micros"
  },
  "avocado": {
    "name":"AH frozen avocado chunks", "grams":125,
    "package":"250 g bag / 2 meals", "package_price":1.99, "cost":1.99/2,
    "url":"https://www.ah.nl/producten/product/wi365661/ah-avocado-stukjes",
    "components":[(9037,125)], "overrides":{"kcal":174*1.25,"protein_g":2*1.25,"carbs_g":1.8*1.25,"fat_g":17*1.25,"saturated_fat_g":2.1*1.25,"fiber_g":3.1*1.25,"sodium_mg":0.2*1.25*1000/2.54},
    "evidence":"Primary AH API label; USDA avocado proxy for wider micros"
  },
  "olive_oil": {
    "name":"AH extra-virgin olive oil", "grams":15,
    "package":"1 litre bottle", "package_price":9.69, "cost":9.69/1000*(15/0.91),
    "url":"https://www.ah.nl/producten/product/wi58043/ah-olijfolie-extra-vierge",
    "components":[(4053,15)], "overrides":{},
    "evidence":"Primary AH API price/label; USDA olive-oil proxy; 0.91 g/ml density for cost"
  },
  "crispy_chili": {
    "name":"Old Mother crispy chilli in oil", "grams":10,
    "package":"210 g jar", "package_price":4.19, "cost":4.19/210*10,
    "url":"https://www.ah.nl/producten/product/wi553362/old-mother-crispy-chili-in-oil",
    "components":[],
    "overrides":{"kcal":71.7,"protein_g":0.59,"carbs_g":0.96,"fat_g":7.11,"saturated_fat_g":1.17,"sodium_mg":2.9*0.1*1000/2.54},
    "evidence":"Primary AH API label; minor micros not modelled"
  },
  "skyr": {
    "name":"Arla Skyr natural 0%", "grams":333,
    "package":"1 kg tub / 3 meals", "package_price":3.99, "cost":3.99/3,
    "url":"https://www.ah.nl/producten/product/wi457983/arla-skyr-naturel-yoghurt-0-vet-xl",
    "components":[(1256,333)],
    "overrides":{"kcal":60*3.33,"protein_g":10*3.33,"carbs_g":4*3.33,"fat_g":0,"saturated_fat_g":0,"sodium_mg":0.14*3.33*1000/2.54},
    "evidence":"Primary AH API Arla label for macros/salt; USDA non-fat plain Greek yoghurt proxy for wider micros"
  },
  "berries": {
    "name":"AH frozen summer-fruit mix", "grams":125,
    "package":"1 kg bag / 8 meals", "package_price":5.55, "cost":5.55/8,
    "url":"https://www.ah.nl/producten/product/wi376520/ah-zakje-met-zomerfruit",
    "components":[(9083,31.25),(9054,25),(9084,25),(9318,25),(9048,12.5),(9518,6.25)],
    "overrides":{"kcal":69*1.25,"protein_g":1*1.25,"carbs_g":13*1.25,"fat_g":0.3*1.25,"saturated_fat_g":0.04*1.25,"fiber_g":5.2*1.25,"sodium_mg":0},
    "evidence":"Primary AH API label and declared 25/20/20/20/10/5% composition; USDA berry proxies for wider micros"
  }
}

COMMON = ["chickpeas","broccoli","asparagus","avocado","olive_oil","crispy_chili","skyr","berries"]

def add_scaled(total, values, grams):
    for key, value in values.items():
        if isinstance(value,(int,float)):
            total[key] = total.get(key,0.0) + value * grams / 100.0

def calculate_item(product):
    total={}
    for food_id, grams in product["components"]:
        add_scaled(total, USDA_SR28[str(food_id)]["nutrients"], grams)
    total.update(product["overrides"])
    return total

def profile(protein_key):
    keys=[protein_key,*COMMON]
    total={}
    for key in keys:
        for nutrient,value in calculate_item(PRODUCTS[key]).items():
            total[nutrient]=total.get(nutrient,0.0)+value
    total["omega3_epa_dha_mg"]=(total.get("omega3_epa_g",0)+total.get("omega3_dha_g",0))*1000
    total["salt_g"]=total.get("sodium_mg",0)*2.54/1000
    rows=[]
    for key,(target,unit,basis) in TARGETS.items():
        value=total.get(key)
        pct=None if value is None else value/target*100
        limit=key in {"sodium_mg","saturated_fat_g"}
        if pct is None: status="unknown"
        elif limit: status="high" if pct>100 else ("watch" if pct>75 else "good")
        else: status="good" if pct>=100 else ("watch" if pct>=75 else "low")
        rows.append({"key":key,"label":LABELS[key],"value":round(value,2) if value is not None else None,"unit":unit,"target":target,"pct":round(pct) if pct is not None else None,"status":status,"basis":basis,"is_limit":limit})
    rows.extend([
      {"key":"iodine_mcg","label":"Iodine","value":None,"unit":"µg","target":150,"pct":None,"status":"unknown","basis":"Not available in SR28/provided labels","is_limit":False},
      {"key":"biotin_mcg","label":"Biotin (B7)","value":None,"unit":"µg","target":30,"pct":None,"status":"unknown","basis":"Sparse source data; not estimated","is_limit":False},
    ])
    cost=sum(PRODUCTS[k]["cost"] for k in keys)
    grams=sum(PRODUCTS[k]["grams"] for k in keys)
    summary={k:round(total.get(k,0),1) for k in ["kcal","protein_g","carbs_g","fat_g","fiber_g","saturated_fat_g","sodium_mg","salt_g","omega3_epa_dha_mg"]}
    return {"protein":protein_key,"name":"Chicken day" if protein_key=="chicken" else "Salmon day","item_keys":keys,"weight_g":grams,"cost_eur":round(cost,2),"summary":summary,"nutrients":rows}

def blend_profiles(chicken, salmon):
    """Daily average for the declared six-chicken/one-salmon week."""
    summary={key:round((chicken["summary"][key]*6+salmon["summary"][key])/7,1) for key in chicken["summary"]}
    salmon_rows={row["key"]:row for row in salmon["nutrients"]}
    rows=[]
    for chicken_row in chicken["nutrients"]:
        salmon_row=salmon_rows[chicken_row["key"]]
        if chicken_row["value"] is None or salmon_row["value"] is None:
            value=pct=None; status="unknown"
        else:
            value=round((chicken_row["value"]*6+salmon_row["value"])/7,2)
            pct=round(value/chicken_row["target"]*100)
            if chicken_row["is_limit"]:
                status="high" if pct>100 else ("watch" if pct>75 else "good")
            else:
                status="good" if pct>=100 else ("watch" if pct>=75 else "low")
        rows.append(chicken_row | {"value":value,"pct":pct,"status":status})
    return {
      "protein":"rotation", "name":"6 + 1 weekly average", "item_keys":["6 × chicken day","1 × salmon day"],
      "weight_g":round((chicken["weight_g"]*6+salmon["weight_g"])/7),
      "cost_eur":round((chicken["cost_eur"]*6+salmon["cost_eur"])/7,2),
      "summary":summary, "nutrients":rows
    }

def build():
    chicken=profile("chicken"); salmon=profile("salmon"); rotation=blend_profiles(chicken,salmon)
    weekly=chicken["cost_eur"]*6+salmon["cost_eur"]
    return {
      "meta":{
        "version":"OMAD V04","generated":"2026-07-14","currency":"EUR","price_basis":"Muscle Meat page and primary AH product API checked 14 July 2026; supermarket prices move.",
        "method":"Branded product labels for energy/macros/salt plus USDA SR28 generic-food proxies for the wider micronutrient panel. Raw/frozen values are summed without cooking-retention factors.",
        "target_profile":"Adult man, age 31–50: US National Academies/NIH RDA or AI where available; sodium 2,300 mg upper limit; EPA+DHA 250 mg display reference.",
        "disclaimer":"Planning estimate, not a diagnosis or substitute for personalised medical or dietetic advice. Product batches, draining, cooking and bioavailability change actual intake."
      },
      "products":[{k:v for k,v in product.items() if k not in {"components","overrides"}} | {"key":key,"cost":round(product["cost"],2)} for key,product in PRODUCTS.items()],
      "profiles":{"chicken":chicken,"salmon":salmon,"rotation":rotation},
      "rotation":{"pattern":"6 chicken + 1 salmon","weekly_cost_eur":round(weekly,2),"average_day_eur":round(weekly/7,2),"thirty_day_eur":round(weekly/7*30,2),"starter_basket_eur":round(sum(product["package_price"] for product in PRODUCTS.values()),2)},
      "sources":[
        {"name":"Muscle Meat chicken label","url":PRODUCTS["chicken"]["url"],"type":"brand label"},
        {"name":"AH primary product API labels/prices","url":"https://www.ah.nl/producten","type":"primary retailer API"},
        {"name":"USDA National Nutrient Database for Standard Reference, Release 28","url":"https://www.ars.usda.gov/ARSUserFiles/80400525/Data/SR/SR28/sr28_doc.pdf","type":"micronutrient proxy"},
        {"name":"NIH Office of Dietary Supplements fact sheets","url":"https://ods.od.nih.gov/factsheets/list-all/","type":"reference intakes"},
        {"name":"Voedingscentrum — fish","url":"https://www.voedingscentrum.nl/encyclopedie/vis.aspx","type":"weekly rotation context"},
        {"name":"AH product pages","url":"https://www.ah.nl/","type":"package and list-price context"}
      ],
      "usda_foods":{fid:{"description":data["description"]} for fid,data in USDA_SR28.items()}
    }

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument("--write",action="store_true")
    parser.add_argument("--check",action="store_true")
    args=parser.parse_args()
    payload=build(); rendered=json.dumps(payload,indent=2,ensure_ascii=False)+"\n"
    if args.write:
        OUTPUT.parent.mkdir(parents=True,exist_ok=True); OUTPUT.write_text(rendered,encoding="utf-8")
        print(f"wrote {OUTPUT}")
    elif args.check:
        if not OUTPUT.exists(): raise SystemExit(f"missing {OUTPUT}; run --write")
        current=OUTPUT.read_text(encoding="utf-8")
        if current!=rendered: raise SystemExit("nutrition-data.json is stale; run --write")
        for key,p in payload["profiles"].items():
            assert p["summary"]["protein_g"] >= 100, (key,p["summary"])
            assert p["summary"]["fiber_g"] >= 30, (key,p["summary"])
            assert p["cost_eur"] > 0
        print(json.dumps({"status":"ok","chicken":payload["profiles"]["chicken"]["summary"],"salmon":payload["profiles"]["salmon"]["summary"],"weekly_cost_eur":payload["rotation"]["weekly_cost_eur"]},ensure_ascii=False))
    else:
        print(json.dumps({k:v["summary"]|{"cost_eur":v["cost_eur"]} for k,v in payload["profiles"].items()},indent=2,ensure_ascii=False))
if __name__ == "__main__": main()
